import os
from pathlib import Path
from collections import defaultdict

DIFFICULTIES = {"Easy": 0, "Medium": 0, "Hard": 0}
TOPICS = defaultdict(lambda: {"Easy": 0, "Medium": 0, "Hard": 0})
PROBLEMS = []

def parse_solution(file_path: Path):
    try:
        content = file_path.read_text(encoding="utf-8")
        difficulty = None
        topic = None
        title = file_path.parent.name  # folder name is problem name

        for line in content.split("\n"):
            line_lower = line.lower().strip()
            if "easy" in line_lower and ("difficulty" in line_lower or "*" in line):
                difficulty = "Easy"
            elif "medium" in line_lower and ("difficulty" in line_lower or "*" in line):
                difficulty = "Medium"
            elif "hard" in line_lower and ("difficulty" in line_lower or "*" in line):
                difficulty = "Hard"

        # Infer topic from folder structure
        parent = str(file_path.parent).lower()
        if any(x in parent for x in ["array", "two-sum", "best-time"]):
            topic = "Arrays"
        elif any(x in parent for x in ["linked-list", "add-two"]):
            topic = "Linked Lists"
        elif any(x in parent for x in ["tree", "binary-tree"]):
            topic = "Trees"
        elif any(x in parent for x in ["string", "palindrome", "anagram"]):
            topic = "Strings"
        elif any(x in parent for x in ["dynamic", "climb", "coin"]):
            topic = "Dynamic Programming"
        elif any(x in parent for x in ["graph", "island", "course"]):
            topic = "Graphs"
        else:
            topic = "Other"

        if difficulty:
            return {"difficulty": difficulty, "topic": topic, "title": title, "file": file_path.name}
    except Exception:
        pass
    return None


# Scan all Python files
for py_file in Path(".").rglob("*.py"):
    if "venv" in str(py_file) or ".github" in str(py_file):
        continue
    result = parse_solution(py_file)
    if result:
        PROBLEMS.append(result)
        diff = result["difficulty"]
        topic = result["topic"]
        if diff in DIFFICULTIES:
            DIFFICULTIES[diff] += 1
        TOPICS[topic][diff] += 1

total = sum(DIFFICULTIES.values())

# Build topic table
topic_rows = ""
topic_totals = {"Easy": 0, "Medium": 0, "Hard": 0}
for topic, counts in sorted(TOPICS.items()):
    e, m, h = counts["Easy"], counts["Medium"], counts["Hard"]
    t = e + m + h
    topic_rows += f"| {topic} | {e} | {m} | {h} | {t} |\n"
    topic_totals["Easy"] += e
    topic_totals["Medium"] += m
    topic_totals["Hard"] += h

te = topic_totals["Easy"]
tm = topic_totals["Medium"]
th = topic_totals["Hard"]
tt = te + tm + th

# Build recent problems list
recent = PROBLEMS[-10:][::-1]
recent_rows = ""
for p in recent:
    recent_rows += f"- `{p['difficulty']}` — {p['title'] or p['file']}\n"

if not recent_rows:
    recent_rows = "_No problems solved yet — start grinding!_\n"

readme = f"""# DSA Practice

Systematic problem-solving practice in Python. Organized by topic and difficulty.

---

## Progress

![Problems Solved](https://img.shields.io/badge/Solved-{total}-brightgreen)
![Easy](https://img.shields.io/badge/Easy-{DIFFICULTIES['Easy']}-green)
![Medium](https://img.shields.io/badge/Medium-{DIFFICULTIES['Medium']}-orange)
![Hard](https://img.shields.io/badge/Hard-{DIFFICULTIES['Hard']}-red)

| Topic | Easy | Medium | Hard | Total |
|---|---|---|---|---|
{topic_rows}| **Total** | **{te}** | **{tm}** | **{th}** | **{tt}** |

---

## Recent Solutions

{recent_rows}
---

## Structure

Each solution file follows this format:
```python
\"\"\"
Problem: <name>
Link: <leetcode url>
Difficulty: Easy / Medium / Hard
Topic: <topic>

Approach: <brief description>
Time: O(?)
Space: O(?)
\"\"\"
```

---

## Order of Study

1. Arrays & Strings
2. Two Pointers
3. Sliding Window
4. Binary Search
5. Linked Lists
6. Stack & Queue
7. Trees
8. Heap
9. Graphs
10. Dynamic Programming
11. Backtracking

---

_Auto-generated by GitHub Actions — updates on every push_
"""

Path("README.md").write_text(readme, encoding="utf-8")
print(f"README updated — {total} problems solved")